'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace dolVFSService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="dolVFSserviceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class dolVFSservice
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CallMMZUOUOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMZUBOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMDROSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMDESTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMFLCAPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMCTCAPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMDOEUOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMCFWDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMCINQOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMMVUOUOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CallMVBNCIOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://dolservicedev/dolVFSService.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CallMMZUOUCompleted As CallMMZUOUCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMZUBOCompleted As CallMMZUBOCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMDROSCompleted As CallMMDROSCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMDESTCompleted As CallMMDESTCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMFLCAPCompleted As CallMFLCAPCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMCTCAPCompleted As CallMCTCAPCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMDOEUCompleted As CallMMDOEUCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMCFWDCompleted As CallMMCFWDCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMCINQCompleted As CallMMCINQCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMMVUOUCompleted As CallMMVUOUCompletedEventHandler
        
        '''<remarks/>
        Public Event CallMVBNCICompleted As CallMVBNCICompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMZUOU", RequestElementName:="Call-MMZUOU", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMZUOUResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMZUOU(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMZUOUResult")> String
            Dim results() As Object = Me.Invoke("CallMMZUOU", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMZUOU(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMZUOU", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMZUOU(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMZUOUAsync(ByVal INPUTVAL As String)
            Me.CallMMZUOUAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMZUOUAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMZUOUOperationCompleted Is Nothing) Then
                Me.CallMMZUOUOperationCompleted = AddressOf Me.OnCallMMZUOUOperationCompleted
            End If
            Me.InvokeAsync("CallMMZUOU", New Object() {INPUTVAL}, Me.CallMMZUOUOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMZUOUOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMZUOUCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMZUOUCompleted(Me, New CallMMZUOUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMZUBO", RequestElementName:="Call-MMZUBO", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMZUBOResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMZUBO(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMZUBOResult")> String
            Dim results() As Object = Me.Invoke("CallMMZUBO", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMZUBO(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMZUBO", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMZUBO(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMZUBOAsync(ByVal INPUTVAL As String)
            Me.CallMMZUBOAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMZUBOAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMZUBOOperationCompleted Is Nothing) Then
                Me.CallMMZUBOOperationCompleted = AddressOf Me.OnCallMMZUBOOperationCompleted
            End If
            Me.InvokeAsync("CallMMZUBO", New Object() {INPUTVAL}, Me.CallMMZUBOOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMZUBOOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMZUBOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMZUBOCompleted(Me, New CallMMZUBOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMDROS", RequestElementName:="Call-MMDROS", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMDROSResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMDROS(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMDROSResult")> String
            Dim results() As Object = Me.Invoke("CallMMDROS", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMDROS(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMDROS", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMDROS(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMDROSAsync(ByVal INPUTVAL As String)
            Me.CallMMDROSAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMDROSAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMDROSOperationCompleted Is Nothing) Then
                Me.CallMMDROSOperationCompleted = AddressOf Me.OnCallMMDROSOperationCompleted
            End If
            Me.InvokeAsync("CallMMDROS", New Object() {INPUTVAL}, Me.CallMMDROSOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMDROSOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMDROSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMDROSCompleted(Me, New CallMMDROSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMDEST", RequestElementName:="Call-MMDEST", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMDESTResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMDEST(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMDESTResult")> String
            Dim results() As Object = Me.Invoke("CallMMDEST", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMDEST(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMDEST", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMDEST(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMDESTAsync(ByVal INPUTVAL As String)
            Me.CallMMDESTAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMDESTAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMDESTOperationCompleted Is Nothing) Then
                Me.CallMMDESTOperationCompleted = AddressOf Me.OnCallMMDESTOperationCompleted
            End If
            Me.InvokeAsync("CallMMDEST", New Object() {INPUTVAL}, Me.CallMMDESTOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMDESTOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMDESTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMDESTCompleted(Me, New CallMMDESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MFLCAP", RequestElementName:="Call-MFLCAP", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MFLCAPResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMFLCAP(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MFLCAPResult")> String
            Dim results() As Object = Me.Invoke("CallMFLCAP", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMFLCAP(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMFLCAP", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMFLCAP(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMFLCAPAsync(ByVal INPUTVAL As String)
            Me.CallMFLCAPAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMFLCAPAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMFLCAPOperationCompleted Is Nothing) Then
                Me.CallMFLCAPOperationCompleted = AddressOf Me.OnCallMFLCAPOperationCompleted
            End If
            Me.InvokeAsync("CallMFLCAP", New Object() {INPUTVAL}, Me.CallMFLCAPOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMFLCAPOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMFLCAPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMFLCAPCompleted(Me, New CallMFLCAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MCTCAP", RequestElementName:="Call-MCTCAP", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MCTCAPResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMCTCAP(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MCTCAPResult")> String
            Dim results() As Object = Me.Invoke("CallMCTCAP", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMCTCAP(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMCTCAP", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMCTCAP(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMCTCAPAsync(ByVal INPUTVAL As String)
            Me.CallMCTCAPAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMCTCAPAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMCTCAPOperationCompleted Is Nothing) Then
                Me.CallMCTCAPOperationCompleted = AddressOf Me.OnCallMCTCAPOperationCompleted
            End If
            Me.InvokeAsync("CallMCTCAP", New Object() {INPUTVAL}, Me.CallMCTCAPOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMCTCAPOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMCTCAPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMCTCAPCompleted(Me, New CallMCTCAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMDOEU", RequestElementName:="Call-MMDOEU", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMDOEUResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMDOEU(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMDOEUResult")> String
            Dim results() As Object = Me.Invoke("CallMMDOEU", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMDOEU(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMDOEU", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMDOEU(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMDOEUAsync(ByVal INPUTVAL As String)
            Me.CallMMDOEUAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMDOEUAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMDOEUOperationCompleted Is Nothing) Then
                Me.CallMMDOEUOperationCompleted = AddressOf Me.OnCallMMDOEUOperationCompleted
            End If
            Me.InvokeAsync("CallMMDOEU", New Object() {INPUTVAL}, Me.CallMMDOEUOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMDOEUOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMDOEUCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMDOEUCompleted(Me, New CallMMDOEUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMCFWD", RequestElementName:="Call-MMCFWD", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMCFWDResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMCFWD(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMCFWDResult")> String
            Dim results() As Object = Me.Invoke("CallMMCFWD", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMCFWD(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMCFWD", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMCFWD(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMCFWDAsync(ByVal INPUTVAL As String)
            Me.CallMMCFWDAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMCFWDAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMCFWDOperationCompleted Is Nothing) Then
                Me.CallMMCFWDOperationCompleted = AddressOf Me.OnCallMMCFWDOperationCompleted
            End If
            Me.InvokeAsync("CallMMCFWD", New Object() {INPUTVAL}, Me.CallMMCFWDOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMCFWDOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMCFWDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMCFWDCompleted(Me, New CallMMCFWDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMCINQ", RequestElementName:="Call-MMCINQ", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMCINQResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMCINQ(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMCINQResult")> String
            Dim results() As Object = Me.Invoke("CallMMCINQ", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMCINQ(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMCINQ", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMCINQ(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMCINQAsync(ByVal INPUTVAL As String)
            Me.CallMMCINQAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMCINQAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMCINQOperationCompleted Is Nothing) Then
                Me.CallMMCINQOperationCompleted = AddressOf Me.OnCallMMCINQOperationCompleted
            End If
            Me.InvokeAsync("CallMMCINQ", New Object() {INPUTVAL}, Me.CallMMCINQOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMCINQOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMCINQCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMCINQCompleted(Me, New CallMMCINQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MMVUOU", RequestElementName:="Call-MMVUOU", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MMVUOUResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMMVUOU(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MMVUOUResult")> String
            Dim results() As Object = Me.Invoke("CallMMVUOU", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMMVUOU(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMMVUOU", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMMVUOU(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMMVUOUAsync(ByVal INPUTVAL As String)
            Me.CallMMVUOUAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMMVUOUAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMMVUOUOperationCompleted Is Nothing) Then
                Me.CallMMVUOUOperationCompleted = AddressOf Me.OnCallMMVUOUOperationCompleted
            End If
            Me.InvokeAsync("CallMMVUOU", New Object() {INPUTVAL}, Me.CallMMVUOUOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMMVUOUOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMMVUOUCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMMVUOUCompleted(Me, New CallMMVUOUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Call-MVBNCI", RequestElementName:="Call-MVBNCI", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Call-MVBNCIResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CallMVBNCI(<System.Xml.Serialization.XmlElementAttribute("INPUT-VAL")> ByVal INPUTVAL As String) As <System.Xml.Serialization.XmlElementAttribute("Call-MVBNCIResult")> String
            Dim results() As Object = Me.Invoke("CallMVBNCI", New Object() {INPUTVAL})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCallMVBNCI(ByVal INPUTVAL As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CallMVBNCI", New Object() {INPUTVAL}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCallMVBNCI(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CallMVBNCIAsync(ByVal INPUTVAL As String)
            Me.CallMVBNCIAsync(INPUTVAL, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CallMVBNCIAsync(ByVal INPUTVAL As String, ByVal userState As Object)
            If (Me.CallMVBNCIOperationCompleted Is Nothing) Then
                Me.CallMVBNCIOperationCompleted = AddressOf Me.OnCallMVBNCIOperationCompleted
            End If
            Me.InvokeAsync("CallMVBNCI", New Object() {INPUTVAL}, Me.CallMVBNCIOperationCompleted, userState)
        End Sub
        
        Private Sub OnCallMVBNCIOperationCompleted(ByVal arg As Object)
            If (Not (Me.CallMVBNCICompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CallMVBNCICompleted(Me, New CallMVBNCICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMZUOUCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMZUOUCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMZUOUCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMZUBOCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMZUBOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMZUBOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMDROSCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMDROSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMDROSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMDESTCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMDESTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMDESTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMFLCAPCompletedEventHandler(ByVal sender As Object, ByVal e As CallMFLCAPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMFLCAPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMCTCAPCompletedEventHandler(ByVal sender As Object, ByVal e As CallMCTCAPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMCTCAPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMDOEUCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMDOEUCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMDOEUCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMCFWDCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMCFWDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMCFWDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMCINQCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMCINQCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMCINQCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMMVUOUCompletedEventHandler(ByVal sender As Object, ByVal e As CallMMVUOUCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMMVUOUCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub CallMVBNCICompletedEventHandler(ByVal sender As Object, ByVal e As CallMVBNCICompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CallMVBNCICompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
